apiVersion: v1
kind: PersistentVolume
metadata:
  name: dga-ckan-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e52420d7e860cd24
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dga-postgres-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e52420d7e860cd24
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 250Gi
  volumeName: dga-ckan-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 250Gi
  volumeName: dga-postgres-pv
